(* Generated by tptp2coqp *)
Require Import SMTCoq.SMTCoq ZArith.
Local Open Scope Z_scope.

(* axioms *)
Variable minus : Z -> Z.
Variable mult : Z -> Z -> Z.
Variable op_0 : Z.
Variable op_a : Z.
Variable op_b : Z.
Variable plus : Z -> Z -> Z.
Variable unit : Z.
Axiom c11 : (mult op_b op_a) = unit.
Axiom c10 : (mult op_a op_b) = unit.
Axiom c09 : forall A : Z, (mult unit A) = A.
Axiom c08 : forall A : Z, (mult A unit) = A.
Axiom c07 : forall A B : Z, (mult A (mult B B)) = (mult (mult A B) B).
Axiom c06 : forall A B C : Z, (mult (mult (mult A B) C) B) = (mult A (mult (mult B C) B)).
Axiom c05 : forall A B C : Z, (mult A (plus B C)) = (plus (mult A B) (mult A C)).
Axiom c04 : forall A : Z, (plus A (minus A)) = op_0.
Axiom c03 : forall A : Z, (plus A op_0) = A.
Axiom c02 : forall A B : Z, (plus A B) = (plus B A).
Axiom c01 : forall A B C : Z, (plus (plus A B) C) = (plus A (plus B C)).

Add_lemmas c11 c10 c09 c08 c07 c06 c05 c04 c03 c02 c01.

(* Goal *)
Theorem check : (mult (mult op_b (mult (mult op_a a) op_b)) op_a) = a.
Proof.
  smt.
Qed.

Check check.

