(* Generated by tptp2coqp *)
Require Import Setoid.
From Completion Require Import Plugin.

(* axioms *)
Parameter G : Set.
Parameter ld : G -> G -> G.
Parameter mult : G -> G -> G.
Parameter rd : G -> G -> G.
Parameter unit : G.
Axiom f08 : forall A B C : G, (mult (mult A B) (mult B (mult C B))) = (mult (mult A (mult B (mult B C))) B).
Axiom f07 : forall A B C : G, (mult (mult (mult A B) A) (mult A C)) = (mult A (mult (mult (mult B A) A) C)).
Axiom f06 : forall A : G, (mult unit A) = A.
Axiom f05 : forall A : G, (mult A unit) = A.
Axiom f04 : forall A B : G, (rd (mult A B) B) = A.
Axiom f03 : forall A B : G, (mult (rd A B) B) = A.
Axiom f02 : forall A B : G, (ld A (mult A B)) = B.
Axiom f01 : forall A B : G, (mult A (ld A B)) = B.

Complete f08 f07 f06 f05 f04 f03 f02 f01 : ld mult rd unit : hint
  for (forall X1 : G, (tuple (mult X1 x0) (mult x0 X1)) = (tuple unit unit)).

(* Goal *)
Theorem check : forall X1 : G, (tuple (mult X1 x0) (mult x0 X1)) = (tuple unit unit).
Proof.
  lpo_autorewrite with hint.
  reflexivity.
Qed.

Check check.

