(* Generated by tptp2coqp *)
Require Import Setoid.
From Completion Require Import Plugin.

(* axioms *)
Parameter G : Set.
Parameter double_divide : G -> G -> G.
Parameter identity : G.
Parameter inverse : G -> G.
Parameter multiply : G -> G -> G.
Axiom identity : forall X : G, identity = (double_divide X (inverse X)).
Axiom inverse : forall X : G, (inverse X) = (double_divide X identity).
Axiom multiply : forall X Y : G, (multiply X Y) = (double_divide (double_divide Y X) identity).
Axiom single_axiom : forall X Y Z : G, (double_divide (double_divide X (double_divide (double_divide identity Y) (double_divide Z (double_divide Y X)))) (double_divide identity identity)) = Z.

Complete identity inverse multiply single_axiom : double_divide identity inverse multiply : hint
  for ((multiply (inverse a1) a1) = identity).

(* Goal *)
Theorem check : (multiply (inverse a1) a1) = identity.
Proof.
  lpo_autorewrite with hint.
  reflexivity.
Qed.

Check check.

