(* Generated by tptp2coqp *)
Require Import SMTCoq.SMTCoq ZArith.
Local Open Scope Z_scope.

(* axioms *)
Variable i : Z -> Z.
Variable ld : Z -> Z -> Z.
Variable mult : Z -> Z -> Z.
Variable rd : Z -> Z -> Z.
Variable unit : Z.
Axiom f11 : forall A B : Z, (mult A B) = (mult B A).
Axiom f10 : forall A : Z, (mult (i A) A) = unit.
Axiom f09 : forall A : Z, (mult A (i A)) = unit.
Axiom f08 : forall A B : Z, (mult (mult A B) (i B)) = A.
Axiom f07 : forall A B C : Z, (mult (mult (mult A B) C) B) = (mult A (mult (mult B C) B)).
Axiom f06 : forall A : Z, (mult unit A) = A.
Axiom f05 : forall A : Z, (mult A unit) = A.
Axiom f04 : forall A B : Z, (rd (mult A B) B) = A.
Axiom f03 : forall A B : Z, (mult (rd A B) B) = A.
Axiom f02 : forall A B : Z, (ld A (mult A B)) = B.
Axiom f01 : forall A B : Z, (mult A (ld A B)) = B.

Add_lemmas f11 f10 f09 f08 f07 f06 f05 f04 f03 f02 f01.

(* Goal *)
Theorem check : (mult a (mult b (mult c b))) = (mult (mult (mult a b) c) b).
Proof.
  smt.
Qed.

Check check.

