(* Generated by tptp2coqp *)
Require Import SMTCoq.SMTCoq ZArith.
Local Open Scope Z_scope.

(* axioms *)
Variable i : Z -> Z.
Variable mult : Z -> Z -> Z.
Variable unit : Z.
Axiom f05 : forall A : Z, (mult (i A) A) = unit.
Axiom f04 : forall A : Z, (mult A (i A)) = unit.
Axiom f03 : forall A B C : Z, (mult A (mult B (mult B C))) = (mult (mult (mult A B) B) C).
Axiom f02 : forall A : Z, (mult unit A) = A.
Axiom f01 : forall A : Z, (mult A unit) = A.

Add_lemmas f05 f04 f03 f02 f01.

(* Goal *)
Theorem check : forall X5 : Z, (mult X5 x4) = x3.
Proof.
  smt.
Qed.

Check check.

