(* Generated by tptp2coqp *)
Require Import Setoid.
From Completion Require Import Plugin.

(* axioms *)
Parameter G : Set.
Parameter identity : G.
Parameter inverse : G -> G.
Parameter multiply : G -> G -> G.
Axiom x_cubed_is_identity : forall X : G, (multiply X (multiply X X)) = identity.
Axiom right_inverse : forall X : G, (multiply X (inverse X)) = identity.
Axiom right_identity : forall X : G, (multiply X identity) = X.
Axiom associativity : forall X Y Z : G, (multiply (multiply X Y) Z) = (multiply X (multiply Y Z)).
Axiom left_inverse : forall X : G, (multiply (inverse X) X) = identity.
Axiom left_identity : forall X : G, (multiply identity X) = X.

Complete x_cubed_is_identity right_inverse right_identity associativity left_inverse left_identity : identity inverse multiply : hint
  for ((multiply a b) = c).

(* Goal *)
Theorem check : (multiply a b) = c.
Proof.
  lpo_autorewrite with hint.
  reflexivity.
Qed.

Check check.

