(* Generated by tptp2coqp *)
Require Import SMTCoq.SMTCoq ZArith.
Local Open Scope Z_scope.

(* axioms *)
Variable identity : Z.
Variable left_inverse : Z -> Z.
Variable multiply : Z -> Z -> Z.
Axiom moufang1 : forall X Y Z : Z, (multiply (multiply X (multiply Y Z)) X) = (multiply (multiply X Y) (multiply Z X)).
Axiom left_inverse : forall X : Z, (multiply (left_inverse X) X) = identity.
Axiom left_identity : forall X : Z, (multiply identity X) = X.

Add_lemmas moufang1 left_inverse left_identity.

(* Goal *)
Theorem check : (multiply (multiply (multiply a b) c) b) = (multiply a (multiply b (multiply c b))).
Proof.
  smt.
Qed.

Check check.

