(* Generated by tptp2coqp *)
Require Import Setoid.
From Completion Require Import Plugin.

(* axioms *)
Parameter G : Set.
Parameter identity : G.
Parameter multiply : G -> G -> G.
Axiom single_axiom2 : (multiply identity identity) = identity.
Axiom single_axiom : forall X Y Z : G, (multiply Y (multiply (multiply Y (multiply (multiply Y Y) (multiply X Z))) (multiply Z (multiply Z Z)))) = X.

Complete single_axiom2 single_axiom : identity multiply : hint
  for ((multiply (multiply a b) c) = (multiply a (multiply b c))).

(* Goal *)
Theorem check : (multiply (multiply a b) c) = (multiply a (multiply b c)).
Proof.
  lpo_autorewrite with hint.
  reflexivity.
Qed.

Check check.

