(* Generated by tptp2coqp *)
Require Import Setoid.
From Hammer Require Import Hammer.

(* axioms *)
Parameter G : Set.
Parameter ld : G -> G -> G.
Parameter mult : G -> G -> G.
Parameter rd : G -> G -> G.
Parameter unit : G.
Axiom c10 : forall A B C : G, (mult (mult A B) (mult C A)) = (mult A (mult (mult B C) A)).
Axiom c09 : forall A B C : G, (mult (mult A B) (mult C A)) = (mult (mult A (mult B C)) A).
Axiom c08 : forall A B C : G, (mult A (mult B (mult C B))) = (mult (mult (mult A B) C) B).
Axiom c07 : forall A B C : G, (mult A (mult B (mult A C))) = (mult (mult (mult A B) A) C).
Axiom c06 : forall A : G, (mult unit A) = A.
Axiom c05 : forall A : G, (mult A unit) = A.
Axiom c04 : forall A B : G, (rd (mult A B) B) = A.
Axiom c03 : forall A B : G, (mult (rd A B) B) = A.
Axiom c02 : forall A B : G, (ld A (mult A B)) = B.
Axiom c01 : forall A B : G, (mult A (ld A B)) = B.


(* Goal *)
Theorem check : (mult (mult a b) (mult c (mult a b))) = (mult (mult (mult a (mult b c)) a) b).
Proof.
  hammer.
Qed.

Check check.

