(* Generated by tptp2coqp *)
Require Import SMTCoq.SMTCoq ZArith.
Local Open Scope Z_scope.

(* axioms *)
Variable ld : Z -> Z -> Z.
Variable mult : Z -> Z -> Z.
Variable rd : Z -> Z -> Z.
Variable unit : Z.
Axiom sos07 : forall A B C : Z, (ld A (mult (mult A B) C)) = (rd (mult B (mult C A)) A).
Axiom sos06 : forall A : Z, (mult unit A) = A.
Axiom sos05 : forall A : Z, (mult A unit) = A.
Axiom sos04 : forall A B : Z, (rd (mult A B) B) = A.
Axiom sos03 : forall A B : Z, (mult (rd A B) B) = A.
Axiom sos02 : forall A B : Z, (ld A (mult A B)) = B.
Axiom sos01 : forall A B : Z, (mult A (ld A B)) = B.

Add_lemmas sos07 sos06 sos05 sos04 sos03 sos02 sos01.

(* Goal *)
Theorem check : (mult (mult (mult a a) b) c) = (mult (mult a a) (mult b c)).
Proof.
  smt.
Qed.

Check check.

