(* Generated by tptp2coqp *)
Require Import Setoid.
From Completion Require Import Plugin.

(* axioms *)
Parameter G : Set.
Parameter i : G -> G.
Parameter ld : G -> G -> G.
Parameter mult : G -> G -> G.
Parameter rd : G -> G -> G.
Parameter unit : G.
Axiom f09 : forall A : G, (i A) = (ld A unit).
Axiom f08 : forall A B C : G, (mult A (mult B C)) = (mult (mult A B) C).
Axiom f07 : forall A B C : G, (mult A (mult B C)) = (mult (mult A B) C).
Axiom f06 : forall A : G, (mult unit A) = A.
Axiom f05 : forall A : G, (mult A unit) = A.
Axiom f04 : forall A B : G, (rd (mult A B) B) = A.
Axiom f03 : forall A B : G, (mult (rd A B) B) = A.
Axiom f02 : forall A B : G, (ld A (mult A B)) = B.
Axiom f01 : forall A B : G, (mult A (ld A B)) = B.

Complete f09 f08 f07 f06 f05 f04 f03 f02 f01 : i ld mult rd unit : hint
  for ((i (mult a b)) = (mult (i b) (i a))).

(* Goal *)
Theorem check : (i (mult a b)) = (mult (i b) (i a)).
Proof.
  lpo_autorewrite with hint.
  reflexivity.
Qed.

Check check.

