(* Generated by tptp2coqp *)
Require Import SMTCoq.SMTCoq ZArith.
Local Open Scope Z_scope.

(* axioms *)
Variable i : Z -> Z.
Variable ld : Z -> Z -> Z.
Variable mult : Z -> Z -> Z.
Variable rd : Z -> Z -> Z.
Variable unit : Z.
Axiom f09 : forall A : Z, (i A) = (ld A unit).
Axiom f08 : forall A B C : Z, (mult A (mult B C)) = (mult (mult A B) C).
Axiom f07 : forall A B C : Z, (mult A (mult B C)) = (mult (mult A B) C).
Axiom f06 : forall A : Z, (mult unit A) = A.
Axiom f05 : forall A : Z, (mult A unit) = A.
Axiom f04 : forall A B : Z, (rd (mult A B) B) = A.
Axiom f03 : forall A B : Z, (mult (rd A B) B) = A.
Axiom f02 : forall A B : Z, (ld A (mult A B)) = B.
Axiom f01 : forall A B : Z, (mult A (ld A B)) = B.

Add_lemmas f09 f08 f07 f06 f05 f04 f03 f02 f01.

(* Goal *)
Theorem check : (i (mult a b)) = (mult (i b) (i a)).
Proof.
  smt.
Qed.

Check check.

