(* Generated by tptp2coqp *)
Require Import SMTCoq.SMTCoq ZArith.
Local Open Scope Z_scope.

(* axioms *)
Variable inverse : Z -> Z.
Variable multiply : Z -> Z -> Z.
Axiom single_axiom : forall A B C : Z, (multiply A (multiply (multiply (inverse (multiply A B)) C) B)) = C.

Add_lemmas single_axiom.

(* Goal *)
Theorem check : (multiply a b) = (multiply b a).
Proof.
  smt.
Qed.

Check check.

