(* Generated by tptp2coqp *)
Require Import Setoid.
From Hammer Require Import Hammer.

(* axioms *)
Parameter G : Set.
Parameter identity : G.
Parameter multiply : G -> G -> G.
Axiom single_axiom2 : (multiply identity identity) = identity.
Axiom single_axiom : forall X Y Z : G, (multiply Y (multiply (multiply Y (multiply (multiply Y Y) (multiply X Z))) (multiply Z (multiply Z Z)))) = X.


(* Goal *)
Theorem check : (multiply a identity) = a.
Proof.
  hammer.
Qed.

Check check.

