(* Generated by tptp2coqp *)
Require Import SMTCoq.SMTCoq ZArith.
Local Open Scope Z_scope.

(* axioms *)
Variable divide : Z -> Z -> Z.
Variable inverse : Z -> Z.
Variable multiply : Z -> Z -> Z.
Axiom multiply : forall X Y : Z, (multiply X Y) = (divide X (inverse Y)).
Axiom single_axiom : forall U X Y Z : Z, (divide (divide X X) (divide Y (divide (divide Z (divide U Y)) (inverse U)))) = Z.

Add_lemmas multiply single_axiom.

(* Goal *)
Theorem check : (multiply (inverse a1) a1) = (multiply (inverse b1) b1).
Proof.
  smt.
Qed.

Check check.

