(* Generated by tptp2coqp *)
Require Import Setoid.
From Hammer Require Import Hammer.

(* axioms *)
Parameter G : Set.
Parameter a : G.
Parameter b : G.
Parameter bigC : G -> G -> G -> G.
Parameter c : G.
Parameter difference : G -> G -> G.
Parameter product : G -> G -> G.
Parameter quotient : G -> G -> G.
Axiom sos09 : (product (product a c) (product c b)) = (product a b).
Axiom sos08 : forall A B C : G, (bigC A B C) = (product (product A B) (product C A)).
Axiom sos07 : forall A B : G, (product (product (product A B) B) (product B (product B A))) = B.
Axiom sos06 : forall A : G, (product A A) = A.
Axiom sos05 : forall A B C D : G, (product (product A B) (product C D)) = (product (product A C) (product B D)).
Axiom sos04 : forall A B : G, (product (quotient A B) B) = A.
Axiom sos03 : forall A B : G, (quotient (product A B) B) = A.
Axiom sos02 : forall A B : G, (product A (difference A B)) = B.
Axiom sos01 : forall A B : G, (difference A (product A B)) = B.


(* Goal *)
Theorem check : (bigC a b x0) = (bigC c c x0).
Proof.
  hammer.
Qed.

Check check.

