(* Generated by tptp2coqp *)
Require Import SMTCoq.SMTCoq ZArith.
Local Open Scope Z_scope.

(* axioms *)
Variable divide : Z -> Z -> Z.
Variable inverse : Z -> Z.
Variable multiply : Z -> Z -> Z.
Axiom inverse : forall A B : Z, (inverse A) = (divide (divide B B) A).
Axiom multiply : forall A B C : Z, (multiply A B) = (divide A (divide (divide C C) B)).
Axiom single_axiom : forall A B C : Z, (divide A (divide (divide A B) (divide C B))) = C.

Add_lemmas inverse multiply single_axiom.

(* Goal *)
Theorem check : (multiply (multiply (inverse b2) b2) a2) = a2.
Proof.
  smt.
Qed.

Check check.

