(* Generated by tptp2coqp *)
Require Import SMTCoq.SMTCoq ZArith.
Local Open Scope Z_scope.

(* axioms *)
Variable minus : Z -> Z.
Variable mult : Z -> Z -> Z.
Variable op_0 : Z.
Variable op_a : Z.
Variable op_b : Z.
Variable plus : Z -> Z -> Z.
Variable unit : Z.
Axiom f11 : (mult op_b op_a) = unit.
Axiom f10 : (mult op_a op_b) = unit.
Axiom f09 : forall A : Z, (mult unit A) = A.
Axiom f08 : forall A : Z, (mult A unit) = A.
Axiom f07 : forall A B : Z, (mult A (mult B B)) = (mult (mult A B) B).
Axiom f06 : forall A B C : Z, (mult (mult (mult A B) C) B) = (mult A (mult (mult B C) B)).
Axiom f05 : forall A B C : Z, (mult A (plus B C)) = (plus (mult A B) (mult A C)).
Axiom f04 : forall A : Z, (plus A (minus A)) = op_0.
Axiom f03 : forall A : Z, (plus A op_0) = A.
Axiom f02 : forall A B : Z, (plus A B) = (plus B A).
Axiom f01 : forall A B C : Z, (plus (plus A B) C) = (plus A (plus B C)).

Add_lemmas f11 f10 f09 f08 f07 f06 f05 f04 f03 f02 f01.

(* Goal *)
Theorem check : (mult (mult x0 op_a) op_b) = x0.
Proof.
  smt.
Qed.

Check check.

