(* Generated by tptp2coqp *)
Require Import SMTCoq.SMTCoq ZArith.
Local Open Scope Z_scope.

(* axioms *)
Variable ld : Z -> Z -> Z.
Variable mult : Z -> Z -> Z.
Variable rd : Z -> Z -> Z.
Variable unit : Z.
Axiom c08 : forall A B C : Z, (mult (mult A B) (ld B (mult C B))) = (mult (mult A C) B).
Axiom c07 : forall A B C : Z, (mult (rd (mult A B) A) (mult A C)) = (mult A (mult B C)).
Axiom c06 : forall A B : Z, (mult (rd A B) B) = A.
Axiom c05 : forall A B : Z, (rd (mult A B) B) = A.
Axiom c04 : forall A B : Z, (ld A (mult A B)) = B.
Axiom c03 : forall A B : Z, (mult A (ld A B)) = B.
Axiom c02 : forall A : Z, (mult A unit) = A.
Axiom c01 : forall A : Z, (mult unit A) = A.

Add_lemmas c08 c07 c06 c05 c04 c03 c02 c01.

(* Goal *)
Theorem check : (mult a (mult b (ld (mult c d) (mult d c)))) = (mult (mult a b) (ld (mult c d) (mult d c))).
Proof.
  smt.
Qed.

Check check.

