(* Generated by tptp2coqp *)
Require Import Setoid.
From Hammer Require Import Hammer.

(* axioms *)
Parameter G : Set.
Parameter identity : G.
Parameter multiply : G -> G -> G.
Axiom single_axiom : forall X Y Z : G, (multiply X (multiply (multiply X (multiply (multiply X Y) Z)) (multiply identity (multiply Z Z)))) = Y.


(* Goal *)
Theorem check : (multiply a (multiply a a)) = identity.
Proof.
  hammer.
Qed.

Check check.

