(* Generated by tptp2coqp *)
Require Import Setoid.
From Hammer Require Import Hammer.

(* axioms *)
Parameter G : Set.
Parameter i : G -> G.
Parameter mult : G -> G -> G.
Parameter unit : G.
Axiom f05 : forall A : G, (mult (i A) A) = unit.
Axiom f04 : forall A : G, (mult A (i A)) = unit.
Axiom f03 : forall A B C : G, (mult A (mult B (mult B C))) = (mult (mult (mult A B) B) C).
Axiom f02 : forall A : G, (mult unit A) = A.
Axiom f01 : forall A : G, (mult A unit) = A.


(* Goal *)
Theorem check : forall X2 : G, (mult x0 X2) = x1.
Proof.
  hammer.
Qed.

Check check.

