(* Generated by tptp2coqp *)
Require Import Setoid.
From Hammer Require Import Hammer.

(* axioms *)
Parameter G : Set.
Parameter a : G.
Parameter b : G.
Parameter equalish : G -> G -> G.
Parameter identity : G.
Parameter ifeq : G -> G -> G -> G -> G.
Parameter inverse : G -> G.
Parameter multiply : G -> G -> G.
Parameter product : G -> G -> G -> G.
Parameter true : G.
Axiom a_equals_b : (equalish a b) = true.
Axiom product_substitution3 : forall W X Y Z : G, (ifeq (equalish X Y) true (ifeq (product W Z X) true (product W Z Y) true) true) = true.
Axiom associativity2 : forall U V W X Y Z : G, (ifeq (product Y Z V) true (ifeq (product X V W) true (ifeq (product X Y U) true (product U Z W) true) true) true) = true.
Axiom associativity1 : forall U V W X Y Z : G, (ifeq (product U Z W) true (ifeq (product Y Z V) true (ifeq (product X Y U) true (product X V W) true) true) true) = true.
Axiom total_function2 : forall W X Y Z : G, (ifeq (product X Y W) true (ifeq (product X Y Z) true (equalish Z W) true) true) = true.
Axiom total_function1 : forall X Y : G, (product X Y (multiply X Y)) = true.
Axiom left_inverse : forall X : G, (product (inverse X) X identity) = true.
Axiom left_identity : forall X : G, (product identity X X) = true.
Axiom ifeq_axiom : forall A B C : G, (ifeq A A B C) = B.


(* Goal *)
Theorem check : (equalish (inverse a) (inverse b)) = true.
Proof.
  hammer.
Qed.

Check check.

