(* Generated by tptp2coqp *)
Require Import Setoid.
From Completion Require Import Plugin.

(* axioms *)
Parameter G : Set.
Parameter i : G -> G.
Parameter ld : G -> G -> G.
Parameter mult : G -> G -> G.
Parameter rd : G -> G -> G.
Parameter unit : G.
Axiom f11 : forall A B : G, (mult A B) = (mult B A).
Axiom f10 : forall A : G, (mult (i A) A) = unit.
Axiom f09 : forall A : G, (mult A (i A)) = unit.
Axiom f08 : forall A B : G, (mult (mult A B) (i B)) = A.
Axiom f07 : forall A B C : G, (mult (mult (mult A B) C) B) = (mult A (mult (mult B C) B)).
Axiom f06 : forall A : G, (mult unit A) = A.
Axiom f05 : forall A : G, (mult A unit) = A.
Axiom f04 : forall A B : G, (rd (mult A B) B) = A.
Axiom f03 : forall A B : G, (mult (rd A B) B) = A.
Axiom f02 : forall A B : G, (ld A (mult A B)) = B.
Axiom f01 : forall A B : G, (mult A (ld A B)) = B.

Complete f11 f10 f09 f08 f07 f06 f05 f04 f03 f02 f01 : i ld mult rd unit : hint
  for ((mult a (mult b (mult a c))) = (mult (mult (mult a b) a) c)).

(* Goal *)
Theorem check : (mult a (mult b (mult a c))) = (mult (mult (mult a b) a) c).
Proof.
  lpo_autorewrite with hint.
  reflexivity.
Qed.

Check check.

