(* Generated by tptp2coqp *)
Require Import Setoid.
From Completion Require Import Plugin.

(* axioms *)
Parameter G : Set.
Parameter ld : G -> G -> G.
Parameter mult : G -> G -> G.
Parameter rd : G -> G -> G.
Axiom f07 : forall A B C : G, (mult (mult A B) (mult C C)) = (mult (mult A C) (mult B C)).
Axiom f06 : forall A B C : G, (mult (mult A A) (mult B C)) = (mult (mult A B) (mult A C)).
Axiom f05 : forall A B C : G, (mult (mult A (mult A A)) (mult B C)) = (mult (mult A B) (mult (mult A A) C)).
Axiom f04 : forall A B : G, (rd (mult A B) B) = A.
Axiom f03 : forall A B : G, (mult (rd A B) B) = A.
Axiom f02 : forall A B : G, (ld A (mult A B)) = B.
Axiom f01 : forall A B : G, (mult A (ld A B)) = B.

Complete f07 f06 f05 f04 f03 f02 f01 : ld mult rd : hint
  for ((mult (mult a b) c) = (mult (mult a c) (mult b (ld c c)))).

(* Goal *)
Theorem check : (mult (mult a b) c) = (mult (mult a c) (mult b (ld c c))).
Proof.
  lpo_autorewrite with hint.
  reflexivity.
Qed.

Check check.

