(* Generated by tptp2coqp *)
Require Import Setoid.
From Completion Require Import Plugin.

(* axioms *)
Parameter G : Set.
Parameter ld : G -> G -> G.
Parameter mult : G -> G -> G.
Parameter rd : G -> G -> G.
Axiom c07 : forall A B : G, (ld A (mult A (ld B B))) = (rd (mult (rd A A) B) B).
Axiom c06 : forall A B C D : G, (rd (mult (mult A B) (rd C D)) (rd C D)) = (mult A (rd (mult B D) D)).
Axiom c05 : forall A B C D : G, (ld (ld A B) (mult (ld A B) (mult C D))) = (mult (ld A (mult A C)) D).
Axiom c04 : forall A B : G, (mult (rd A B) B) = (rd (mult A B) B).
Axiom c03 : forall A B : G, (mult A (ld A B)) = (ld A (mult A B)).
Axiom c02 : forall A : G, (rd (mult A A) A) = A.
Axiom c01 : forall A : G, (ld A (mult A A)) = A.

Complete c07 c06 c05 c04 c03 c02 c01 : ld mult rd : hint
  for ((rd (mult a (mult b c)) (mult b c)) = (rd (mult a c) c)).

(* Goal *)
Theorem check : (rd (mult a (mult b c)) (mult b c)) = (rd (mult a c) c).
Proof.
  lpo_autorewrite with hint.
  reflexivity.
Qed.

Check check.

