(* Generated by tptp2coqp *)
Require Import Setoid.
From Completion Require Import Plugin.

(* axioms *)
Parameter G : Set.
Parameter identity : G.
Parameter inverse : G -> G.
Parameter multiply : G -> G -> G.
Axiom left_inverse : forall X : G, (multiply (inverse X) X) = identity.
Axiom left_identity : forall X : G, (multiply identity X) = X.
Axiom associativity : forall X Y Z : G, (multiply (multiply X Y) Z) = (multiply X (multiply Y Z)).

Complete left_inverse left_identity associativity : identity inverse multiply : hint
  for ((multiply b c) = (multiply d c)).

(* Goal *)
Theorem check : (multiply b c) = (multiply d c).
Proof.
  lpo_autorewrite with hint.
  reflexivity.
Qed.

Check check.

