(* Generated by tptp2coqp *)
Require Import SMTCoq.SMTCoq ZArith.
Local Open Scope Z_scope.

(* axioms *)
Variable ld : Z -> Z -> Z.
Variable mult : Z -> Z -> Z.
Variable s : Z -> Z.
Variable unit : Z.
Axiom c09 : forall A B : Z, (mult A B) = (mult B A).
Axiom c08 : forall A : Z, (s (mult A A)) = A.
Axiom c07 : forall A : Z, (mult (s A) (s A)) = A.
Axiom c06 : forall A B C : Z, (ld A (mult (mult B C) A)) = (mult (ld A (mult B A)) (ld A (mult C A))).
Axiom c05 : forall A B C D : Z, (ld (mult A B) (mult A (mult B (mult C D)))) = (mult (ld (mult A B) (mult A (mult B C))) (ld (mult A B) (mult A (mult B D)))).
Axiom c04 : forall A B : Z, (ld A (mult A B)) = B.
Axiom c03 : forall A B : Z, (mult A (ld A B)) = B.
Axiom c02 : forall A : Z, (mult unit A) = A.
Axiom c01 : forall A : Z, (mult A unit) = A.

Add_lemmas c09 c08 c07 c06 c05 c04 c03 c02 c01.

(* Goal *)
Theorem check : (mult (mult a b) c) = (mult a (mult b c)).
Proof.
  smt.
Qed.

Check check.

