(* Generated by tptp2coqp *)
Require Import Setoid.
From Hammer Require Import Hammer.

(* axioms *)
Parameter G : Set.
Parameter identity : G.
Parameter multiply : G -> G -> G.
Axiom left_identity : forall X : G, (multiply identity X) = X.
Axiom associativity : forall X Y Z : G, (multiply (multiply X Y) Z) = (multiply X (multiply Y Z)).


(* Goal *)
Theorem check : forall X : G, (multiply X X) = identity.
Proof.
  hammer.
Qed.

Check check.

