(* Generated by tptp2coqp *)
Require Import SMTCoq.SMTCoq ZArith.
Local Open Scope Z_scope.

(* axioms *)
Variable identity : Z.
Variable multiply : Z -> Z -> Z.
Axiom left_identity : forall X : Z, (multiply identity X) = X.
Axiom associativity : forall X Y Z : Z, (multiply (multiply X Y) Z) = (multiply X (multiply Y Z)).

Add_lemmas left_identity associativity.

(* Goal *)
Theorem check : forall X : Z, (multiply X X) = identity.
Proof.
  smt.
Qed.

Check check.

